name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    types:
      - opened
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name : instal dependency
      run: npm i

    - name : Show Start time
      run: echo "Pipeline started at $(date)"

    - name : run lint and prittier to fix the code  
      run: npm run code:fix

    - name : test the code with jest
      run: npm run test

    - name: build code
      run: npm run build
     
    - name: Show End Time
      run: echo "Pipeline ended at $(date)"

    - name: Show Success Message
      run: echo "PIPELINE SUCCESS WITHOUT ERRORS"