name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4


    - name : instal dependency
      run: npm i
    - run: npm init @eslint/config

    - name : display Start time
      run: echo "Pipeline started at $(date)"

    - name : run lint and prittier to fix the code  
      run: npm run code:fix

    - name : test the code with jest
      run: npm run test

    - name: build the code
      run : npm run build

    - name: Display End Time
      run: echo "Pipeline ended at $(date)"